### ISSUE TITLE
ignores

### ISSUE THREAD

**Issue by ARS81** [poppinlp/grunt-static-version#1]
Hi! I'm confused about the ignore option. Trying to use it for this line to ignore

``` html
<link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/sandstone/bootstrap.min.css" rel="stylesheet">
```

but in console there's always a warn saying "File not found".
What should be the ignore item for this situation?
Btw, thanks for the plugin, nice approach!

**Comment by poppinlp** [comment]
Sorry for my late reply.

`ignore` option is added for ignore templates variables, such as:

```html
<link href="{{some templates code}}/path/to/file" rel="stylesheet">
```

I'm working on it to update this plugin. `ignore` and `output` option will be like this [README](https://github.com/poppinlp/grunt-static-version/tree/dev#filesignore-object).

**Comment by poppinlp** [comment]
Hi. This feature is now added at version 0.0.6.
Thanks for issue.
